#!/usr/bin/env python3
"""Bundle a notebook with the algoviz package for the browser build.

``marimo export html-wasm`` only embeds the notebook's own source. This writes
a copy of the notebook with:

1. a PEP 723 header listing the packages to install in the browser, and
2. a first cell that unpacks ``algoviz/`` and the notebook's ``pseudocode/``
   folder and puts them on ``sys.path``.

The notebook's import cell is made to depend on that cell so it runs first.

    python3 utils/bundle_wasm.py notebooks/array_sorting.py -o build/standalone
"""

from __future__ import annotations

import argparse
import ast
import base64
import re
import shutil
import sys
from pathlib import Path

# Packages installed in the browser. marimo is the runtime and numpy comes
# with matplotlib; networkx is only needed for graph layouts.
GRAPH_USE = re.compile(r"\bgraph_(?:source|from_text)\b")
PRESET_USE = re.compile(r"from algoviz\.presets import (\w+)")
CSS_FILE = re.compile(r'\bcss_file="([^"]+)"')


def dependencies(source: str) -> list[str]:
    """Packages the notebook needs installed in the browser."""
    return ["matplotlib", "pillow", "scienceplots"] + (
        ["networkx"] if GRAPH_USE.search(source) else []
    )

READY_FLAG = "ALGOVIZ_READY"

PEP723 = """# /// script
# requires-python = ">=3.9"
# dependencies = [
{deps}
# ]
# ///
"""

BOOTSTRAP = '''

@app.cell
def _():
    # Generated by utils/bundle_wasm.py. Unpacks algoviz into a temp
    # directory and adds it to sys.path. Files are base64 so marimo's
    # indentation handling cannot alter them.
    import base64 as _b64
    import os as _os
    import sys as _sys
    import tempfile as _tempfile

    _BUNDLE = {{
{entries}
    }}
    _root = _os.path.join(_tempfile.gettempdir(), "algoviz_bundle")
    for _path, _blob in _BUNDLE.items():
        _target = _os.path.join(_root, _path)
        _os.makedirs(_os.path.dirname(_target), exist_ok=True)
        with open(_target, "wb") as _fh:
            _fh.write(_b64.b64decode(_blob))
    if _root not in _sys.path:
        _sys.path.insert(0, _root)
    {flag} = _root
    return ({flag},)
'''


def package_files(root: Path, topic: str | None) -> dict[str, bytes]:
    """Files to bundle: ``algoviz/`` and the notebook's ``pseudocode/`` folder."""
    if not (root / "algoviz").is_dir():
        raise SystemExit(f"no algoviz package under {root}")
    paths = list((root / "algoviz").rglob("*.py"))
    if topic:
        paths += (root / "pseudocode" / topic).glob("*.py")
    return {
        p.relative_to(root).as_posix(): p.read_bytes()
        for p in sorted(paths)
        if "__pycache__" not in p.parts
    }


def import_cell(source: str) -> ast.FunctionDef | None:
    """The @app.cell function that imports algoviz, if there is one."""
    for node in ast.walk(ast.parse(source)):
        if not isinstance(node, ast.FunctionDef):
            continue
        segment = ast.get_source_segment(source, node) or ""
        if "import algoviz" in segment or "from algoviz" in segment:
            return node
    return None


def add_dependency(source: str, node: ast.FunctionDef, name: str) -> str:
    """Make a cell depend on ``name`` so it runs after the bootstrap cell.

    marimo reads dependencies from the cell body, so the name is referenced
    there as well as added to the signature.
    """
    lines = source.split("\n")

    # Signature.
    index = node.lineno - 1
    line = lines[index]
    if "def _()" in line:
        lines[index] = line.replace("def _()", f"def _({name})")
    elif "def _(" in line:
        lines[index] = line.replace("def _(", f"def _({name}, ", 1)
    else:
        raise SystemExit(f"cannot parse cell signature: {line!r}")

    # Reference in the body.
    first = node.body[0]
    indent = " " * first.col_offset
    lines.insert(
        first.lineno - 1,
        f"{indent}{name}  # generated: runs after the bundle cell",
    )
    return "\n".join(lines)


def bundle(notebook: Path, root: Path) -> str:
    source = notebook.read_text()

    target = import_cell(source)
    if target is None:
        print(f"  {notebook.name}: no algoviz import, only adding the header")
        entries_block = None
    else:
        source = add_dependency(source, target, READY_FLAG)
        topic = PRESET_USE.search(source)
        files = package_files(root, topic.group(1) if topic else None)
        entries_block = "\n".join(
            f'        "{path}": "{base64.b64encode(blob).decode()}",'
            for path, blob in files.items()
        )
        total = sum(len(v) for v in files.values())
        print(f"  {notebook.name}: bundled {len(files)} files ({total:,} bytes)")

    header = PEP723.format(
        deps="\n".join(f'#     "{dep}",' for dep in dependencies(source))
    )
    out = header + source
    if entries_block is not None:
        marker = '\nif __name__ == "__main__":'
        cell = BOOTSTRAP.format(entries=entries_block, flag=READY_FLAG)
        if marker in out:
            out = out.replace(marker, cell + marker, 1)
        else:
            out = out + cell
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("notebooks", nargs="+", type=Path)
    parser.add_argument("-o", "--output", type=Path,
                        default=Path("build/standalone"))
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    args.output.mkdir(parents=True, exist_ok=True)

    print(f"bundling into {args.output}/")
    for notebook in args.notebooks:
        if not notebook.exists():
            raise SystemExit(f"no such notebook: {notebook}")
        text = bundle(notebook, root)
        # css_file is relative to the notebook; copy the sheet beside the
        # bundled copy and point at it there.
        css = CSS_FILE.search(text)
        if css:
            sheet = Path(css.group(1)).name
            shutil.copyfile(notebook.parent / css.group(1), args.output / sheet)
            text = text.replace(css.group(0), f'css_file="{sheet}"')
        destination = args.output / notebook.name
        destination.write_text(text)
        # Catch syntax errors here rather than in the browser.
        try:
            compile(text, str(destination), "exec")
        except SyntaxError as exc:
            raise SystemExit(
                f"{destination}: generated file is invalid Python: "
                f"{exc.msg} (line {exc.lineno})"
            ) from exc
        print(f"  -> {destination} ({len(text):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
